-- Solution 1.

WITH RECURSIVE SERIALNUMBERS AS
	(SELECT 330115 AS SERIAL_NO
		UNION ALL SELECT SERIAL_NO + 1
		FROM SERIALNUMBERS
		WHERE SERIAL_NO < 330125 )
SELECT L.SERIAL_NO AS MISSING_SERTIAL_NO
FROM SERIALNUMBERS L
LEFT JOIN INVOICETABLE R ON L.SERIAL_NO = R.SERIAL_NO
WHERE R.SERIAL_NO IS NULL
ORDER BY L.SERIAL_NO;


-- Solution 2: Simple approach

SELECT GENERATE_SERIES(330115, 330125) AS MISSING_SERTIAL_NO
EXCEPT
SELECT SERIAL_NO
FROM INVOICETABLE
ORDER BY 1;


-- Solution 3: Another simple approach

SELECT GENERATE_SERIES(min(SERIAL_NO), max(SERIAL_NO)) AS MISSING_SERTIAL_NO
FROM INVOICETABLE
EXCEPT 
SELECT SERIAL_NO
FROM INVOICETABLE
ORDER BY 1;